AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function to retrieve AWS-published ip-ranges.json and update a security group egress rules
Resources:
  IPManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: python3.6
      Timeout: 10
